

food:

  columns:

    Price_System:
      1363:
        type: categorical
        categories:
          Free_Price:       {Provision_Method: Purchase_Free_Price}
          Subsidised_Price: {Provision_Method: Purchase_Subsidised_Price}
      1369: null

    Provision_Method:
      1363:
        type: categorical
        categories:
          Purchase: [Purchase_Free_Price, Purchase_Subsidised_Price]
      1369: null

    Amount:
      1363:
        type: numerical
        expression: "Kilos"
      1383:
        type: numerical
        expression: "0.001 * Grams + Kilos"

  order:
    - Year
    - ID
    - Code
    - Provision_Method
    - Price_System
    - Amount
    - Price
    - Expenditure
