site_name: HBSIR
site_url: https://iran-open-data.github.io/HBSIR/
repo_url: https://github.com/Iran-Open-Data/HBSIR

theme:
  name: material
  features:
    # - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    # - toc.follow
    # - toc.integrate

nav:
  - Home: README.md
  - Tables:
    - tables/README.md
    - Raw Tables:
      - tables/raw/index.md
      - General Tables:
        - Household Information: tables/raw/household_information.md
        - Members Properties: tables/raw/members_properties.md
        - House Specifications: tables/raw/house_specifications.md
      - Expenditure Tables:
        - Food: tables/raw/food.md
        - Tobacco: tables/raw/tobacco.md
        - Cloth: tables/raw/cloth.md
        - Home: tables/raw/home.md
        - Furniture: tables/raw/furniture.md
        - Medical: tables/raw/medical.md
        - Transportation: tables/raw/transportation.md
        - Communication: tables/raw/communication.md
        - Entertainment: tables/raw/entertainment.md
        - Education: tables/raw/education.md
        - Hotel: tables/raw/hotel.md
        - Miscellaneous: tables/raw/miscellaneous.md
        - Durable: tables/raw/durable.md
        - Investment: tables/raw/investment.md
      - Income Tables:
        - Employment Income: tables/raw/employment_income.md
        - Self Employed Income: tables/raw/self_employed_income.md
        - Other Incomes: tables/raw/other_income.md
        - Subsidy: tables/raw/subsidy.md
        - Employment Income (Old, Public): tables/raw/public_employment_income.md
        - Employment Income (Old, Private): tables/raw/private_employment_income.md
        - Self Employed Income (Old, Agricultural): tables/raw/agricultural_self_employed_income.md
        - Self Employed Income (Old, Non-Agricultural): tables/raw/non_agricultural_self_employed_income.md
        - Other Income (Old): tables/raw/old_other_income.md


plugins:
  - search
  - autorefs
  # - literate-nav:
  #     nav_file: index.md
  #     implicit_index: true