
# Package Settings
package_settings: "config/settings.yaml"

# Local Settings
local_settings: settings.yaml

# Package Metadata
package_metadata:
  instruction: "metadata/_instruction.yaml"
  tables: "metadata/tables.yaml"
  maps: "metadata/maps.yaml"
  household: "metadata/household.yaml"
  commodities: "metadata/commodities.yaml"
  occupations: "metadata/occupations.yaml"
  schema: "metadata/schema.yaml"
  other: "metadata/other.yaml"
  external_data: "metadata/external_data.yaml"

# Local Metadata
local_metadata:
  instruction: "metadata/_instruction.yaml"
  tables: "metadata/tables.yaml"
  maps: "metadata/maps.yaml"
  household: "metadata/household.yaml"
  commodities: "metadata/commodities.yaml"
  occupations: "metadata/occupations.yaml"
  schema: "metadata/schema.yaml"
  other: "metadata/other.yaml"
  external_data: "metadata/external_data.yaml"

# Local Directorie
local_directory: Data
in_root: False

# Online Directory
online_directory: "https://s3.ir-tbz-sh1.arvanstorage.ir/sdac/HBSIR"

# Years
first_year: 1363
last_year: 1401

# Folder Names
archive_files: 1_archive_files
unpacked_data: 2_unpacked_data
extracted_data: 3_extracted_data
processed_data: processed_data
external_data: external_data
maps: maps
cached_data: _cache

# Map
default_map: humandata

# Functions
functions_defaults:
  # Load Table
  load_table:
    dataset: processed
    on_missing: download
    save_downloaded: true
    redownload: false
    save_created: true
    recreate: false

# Column Names
columns:
  year: Year
  household_id: ID
  commodity_code: Code
  job_code: Job_Code
