

ANCHORS:

  common_expenditure_order: &common_expenditure_order
    - Year
    - ID
    - Code
    - Provision_Method
    - Price_System
    - Amount
    - Duration
    - Price
    - Expenditure
    - Secondhand_Sale


household_information:

  instructions:

    - apply_order:
      - Year
      - ID
      - Season
      - Weight	


house_specifications:

  instructions:

    - add_year


food:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        1363:
          name: Price_System
          type: categorical
          categories:
            Free_Price:       {Provision_Method: Purchase_Free_Price}
            Subsidised_Price: {Provision_Method: Purchase_Subsidised_Price}
        1369: null

    - create_column:
        1363:
          name: Price_System
          type: categorical
          categories:
            Purchase: [Purchase_Free_Price, Purchase_Subsidised_Price]
        1369: null

    - create_column:
        name: Amount
        type: numerical
        versions:
          1363:
            expression: "Kilos"
          1383:
            expression: "Kilos + 0.001 * Grams"

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original



tobacco:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original



cloth:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original


home:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original


furniture:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original


medical:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original


transportation:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original


communication:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original


entertainment:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original


education:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original


hotel:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original


other:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 30

    - apply_order: *common_expenditure_order

  views:
   - original


durable:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 360

    - apply_order: *common_expenditure_order

  views:
   - original


investment:

  instructions:

    - add_year

    - add_table_name

    - create_column:
        name: Duration
        type: numerical
        expression: 360

    - apply_order: *common_expenditure_order

  views:
   - original


Weights:

  table_list:

    - house_specifications

  instructions:

    - add_weights

    - apply_order:
      - Year
      - ID
      - Weight


Original_Expenditures:

  table_list:
    - food
    - tobacco
    - cloth
    - home
    - furniture
    - medical
    - transportation
    - communication
    - entertainment
    - education
    - hotel
    - other
    - durable

  instructions:
    - create_column:
        name: Gross_Expenditure
        type: numerical
        expression: "Expenditure"

    - create_column:
        name: Net_Expenditure
        type: numerical
        expression: "Expenditure - Secondhand_Sale"

    - apply_order:
      - Year
      - ID
      - Table_Name
      - Code
      - Provision_Method
      - Price_System
      - Amount
      - Duration
      - Price
      - Gross_Expenditure
      - Net_Expenditure


Expenditures:

  table_list:
    - Original_Expenditures

  instructions:
    - create_column:
        name: Gross_Expenditure
        type: numerical
        expression: "Gross_Expenditure / Duration * 360"

    - create_column:
        name: Net_Expenditure
        type: numerical
        expression: "Net_Expenditure / Duration * 360"
        
    - apply_order:
      - Year
      - ID
      - Code
      - Provision_Method
      - Price_System
      - Amount
      - Price
      - Gross_Expenditure
      - Net_Expenditure


Original_Outlays:
  table_list:
    - Original_Expenditures

  instructions:
    - apply_filter: "Provision_Method != 'Purchase' & Provision_Method.notnull()"


Outlays:
  table_list:
    - Expenditures

  instructions:
    - apply_filter: "Provision_Method != 'Purchase' & Provision_Method.notnull()"


# employment_income:
#   {}


# self_employed_income:
#   {}


# other_income:

#   columns:
#     Other_Incomes:
#       type: numerical
#       expression: "Retirement + Rent + Interest + Aid + Home_Production + Transfer"


# _long_other_incomes:
#   settings:
#     add_table_names: false

#   table_list:
#     - other_income

#   preprocessing:
#     - "table.set_index(['Year', 'ID', 'Member_Number'])"
#     - "table.stack().to_frame().reset_index()"
#     - "table.set_axis(['Year', 'ID', 'Member_Number', 'type', 'value'], axis='columns')"

#   columns:
#     Other_Incomes:
#       type: numerical
#       expression: "value"

#     Other_Income_Type:
#       type: categorical
#       categories:
#         Retirement:        {type: Retirement}
#         Rent:              {type: Rent}
#         Interest:          {type: Interest}
#         Aid:               {type: Aid}
#         Home_Production:   {type: Home_Production}
#         Transfer:          {type: Transfer}

#   filter:
#     "Other_Incomes > 0"

#   order:
#     - Year
#     - ID
#     - Member_Number
#     - Other_Incomes
#     - Other_Income_Type


# subsidy:
#   {}


# public_employment_income:
#   {}


# private_employment_income:
#   {}


# Imputed_Rent:

#   table_list:
#     - home

#   classifications:
#     - {classification: Imputed_Rent, attribute: is_imputed, dropna: true}

#   columns:
#     Income:
#       type: numerical
#       expression: "Expenditure * Imputed_Rent * 12"

#     Income_Type:
#       type: categorical
#       categories:
#         NonCash_ImputedRent: null

#   order:
#     - Year
#     - ID
#     - Income_Type
#     - Income


# NonCash_Incomes_Excluding_Imputed_Rent:

#   table_list:
#     - Outlays

#   columns:
#     Income:
#       type: numerical
#       expression: "Net_Expenditure"

#     Income_Type:
#       type: categorical
#       categories:
#         NonCash_Private:          {Provision_Method: Instead_of_Private_Service}
#         NonCash_Public:           {Provision_Method: Instead_of_Public_Service}
#         NonCash_Cooperative:      {Provision_Method: Instead_of_Cooperative_Service}
#         NonCash_Agricultural:     {Provision_Method: Agricultural_Work}
#         NonCash_NonAgricultural:  {Provision_Method: Non_Agricultural_Work}
#         NonCash_Donation:         {Provision_Method: Donation}   
#         NonCash_HomeProduction:   {Provision_Method: Home_Production}   

#   filter: "Provision_Method not in ['Purchase']"

#   order:
#     - Year
#     - ID
#     - Income_Type
#     - Income


# NonCash_Incomes:

#   table_list:
#     - Imputed_Rent
#     - NonCash_Incomes_Excluding_Imputed_Rent

#   order:
#     - Year
#     - ID
#     - Income_Type
#     - Income


# Direct_Cash_Incomes:
#   settings:
#     add_table_names: true

#   table_list:
#     - employment_income
#     - self_employed_income
#     - _long_other_incomes
#     - subsidy
#     - investment

#   columns:
#     Income:
#       type: numerical
#       expression: "Yearly_Net_Income + Profit + Other_Incomes + Subsidy + Secondhand_Sale"

#     Income_Type:
#       type: categorical
#       categories:
#         Cash_Public:              {table: employment_income, Sector: Public}
#         Cash_Private:             {table: employment_income, Sector: Private}
#         Cash_Cooperative:         {table: employment_income, Sector: Cooperative}
#         Cash_Agricultural:        {table: self_employed_income, Is_Agricultural: true}
#         Cash_NonAgricultural:     {table: self_employed_income, Is_Agricultural: false}
#         Cash_Retirement:          {Other_Income_Type: Retirement}
#         Cash_Rent:                {Other_Income_Type: Rent}
#         Cash_Interest:            {Other_Income_Type: Interest}
#         Cash_Aid:                 {Other_Income_Type: Aid}
#         Cash_Home_Production:     {Other_Income_Type: Home_Production}
#         Cash_Transfer:            {Other_Income_Type: Transfer}
#         Cash_Subsidy:             {table: subsidy}
#         Cash_Investment_Disposal: {table: investment}

#   order:
#     - Year
#     - ID
#     - Member_Number
#     - Income_Type
#     - Income


# Indirect_Cash_Income:

#   table_list:
#     - durable

#   classifications:
#     - {classification: Insurance_Benefits, attribute: is_benefit, dropna: true}

#   filter: "Provision_Method in ['Purchase']"

#   columns:
#     Income:
#       type: numerical
#       expression: "Expenditure"

#     Income_Type:
#       type: categorical
#       categories:
#         Cash_Insurance_Benefits: null

#   order:
#     - Year
#     - ID
#     - Member_Number
#     - Income_Type
#     - Income


# Cash_Incomes:
#   table_list:
#     - Direct_Cash_Incomes
#     - Indirect_Cash_Income

#   order:
#     - Year
#     - ID
#     - Member_Number
#     - Income_Type
#     - Income


# Incomes:
#   table_list:
#     - NonCash_Incomes
#     - Cash_Incomes

#   order:
#     - Year
#     - ID
#     - Member_Number
#     - Income_Type
#     - Income
