name: Poetry build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install unixodbc
      run: sudo apt-get install unixodbc-dev

    - name: install odbc-mdbtools
      run: sudo apt install odbc-mdbtools

    - name: Install poetry
      run: pip install poetry

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'poetry'

    - name: Install dependencies
      run: poetry install

    - name: Install pytest
      run: poetry add pytest

    - name: Test with pytest
      run: poetry run pytest tests/
